import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Poppins } from "next/font/google";
import Header from "./components/Header";
import { Bricolage_Grotesque } from "next/font/google";
import { Saira } from "next/font/google";
import Footer from './components/Footer';
import 'swiper/css'
import '../../public/sass/base/base.scss';
import '../../public/sass/base/helper.scss';
import '../../public/sass/base/reset.scss';
import { headers } from 'next/headers';

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    preload: true,
    display: "swap"
});

const saira = Saira({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    preload: true,
    variable: '--font-bricologe',
    display: "swap"
});

const bricologe = Bricolage_Grotesque({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800"],
    preload: true,
    variable: '--font-bricologe',
    display: "swap"
});

export const metadata = {
    title: "Saynt AI",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const curHeaders = await headers();
    const currentUrl = curHeaders.get('X-Current-URL');

    if(currentUrl.includes("admin"))
    {
        return (
            <html lang="en">
                <body id='pb_scroll' className={`${poppins.className} ${bricologe.variable} ${saira.variable}`}>
                    {children}
                </body>
            </html>
        )
    }
    else
    {
        return (
            <html lang="en">
                <body id='pb_scroll' className={`${poppins.className} ${bricologe.variable} ${saira.variable}`}>
                    <Header />
                    {children}
                    <Footer />
                </body>
            </html>
        );
    }
    
}
