import { Poppins } from "next/font/google";
import '../../public/sass/base/base.scss';
import '../../public/sass/base/helper.scss';
import '../../public/sass/base/reset.scss';


const poppins = Poppins({
  subsets: ["latin"],
  weight:["100","200","300","400","500","600","700","800","900"],
  preload: true,
  display:"swap"
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        {children}
      </body>
    </html>
  );
}
